### ISSUE TITLE
Enable the mail option in contributors tab

### ISSUE THREAD

**Issue by swamitagupta** [ACM-VIT/iOS-Feature-Park#12]
**Describe the bug**
The mail option in the contributors context menu doesn't open a mailing window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Tap on the contributors tab.
2. Long press on a contributor to make the context menu appear.
3. Tap on the mail option.
4. It does not lead you to draft a mail.

**Expected behaviour**
On tapping the mail option, a new window should open where you can draft your mail.

**Testing (please complete the following information):**
 - Device: iPhone11
 - iOS: 14.0
 - Xcode: 12.0

**Additional context**
You may refer to [MessageUI](https://developer.apple.com/documentation/messageui)

**Comment by maxnatchanon** [comment]
Hi, @swamitagupta. Could I work on this? 😀

**Comment by swamitagupta** [comment]
> Hi, @swamitagupta. Could I work on this? 😀

Sure! Assigned :)
