### ISSUE TITLE
Fix framework cell height

### ISSUE THREAD

**Issue by maxnatchanon** [ACM-VIT/iOS-Feature-Park#14]
**Describe the bug**
Framework tab currently has a fixed height of 80, which make the subtitle of some rows overflow.  

**To Reproduce**
1. Go to 'Frameworks' tab
2. See error

**Expected behavior**
The cell's height should be dynamic and expand with its subtitle.

**Screenshots**
<img src="https://user-images.githubusercontent.com/44316949/95659406-02a8c600-0b4b-11eb-83b6-033879f9b588.png" width="400px">

**Testing (please complete the following information):**
 - Device: iPhone 11 Pro
 - iOS: 14.0.1
 - Xcode 12.0

**Comment by NiklasOemler** [comment]
I can do that !
