### ISSUE TITLE
Add Searchbar for searching.

### ISSUE THREAD

**Issue by aaryankotharii** [ACM-VIT/iOS-Feature-Park#3]
**Is your feature request related to a problem? Please describe.**
It would be great if the app had a way to search through all the contributors instead of scrolling all the way down.

**Describe the solution you'd like**
A search bar under the navigation bar would be really helpful. So I can search for keywords and the list below filters accordingly.

**Describe alternatives you've considered**
N/A

**Additional context**
A [UIsearchcontroller](https://developer.apple.com/documentation/uikit/uisearchcontroller) shall be used to implement the same.

**Comment by NiklasOemler** [comment]
Hello @aaryankotharii again , this issues is perfect for me to learn the API of UISearchController. 
Can I get this issue?

**Comment by aaryankotharii** [comment]
Sure @NiklasOemler!
Assigned.
