### ISSUE TITLE
Implement SafariServices

### ISSUE THREAD

**Issue by swamitagupta** [ACM-VIT/iOS-Feature-Park#7]
**Is your feature request related to a problem? Please describe.**
It would be great if you could show the implementation of SafariServices when tapped on in the tableView.

**Describe the solution you'd like**
Tapping on SafariServices leads you to a Blank View Controller. Show your implementation there.

**Describe alternatives you've considered**
N/A

**Additional context**
You may refer to [SafariServices](https://developer.apple.com/documentation/safariservices)

**Comment by FraDeliro** [comment]
I would like to take this one :)
